# Generated by Django 2.2.4 on 2019-08-13 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptops101', '0002_auto_20190811_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='TAG',
        ),
        migrations.AddField(
            model_name='laptop',
            name='ASSET_TAG',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='ASSIGNED_USER',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laptops101.EndUser'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='PURCHASE_COST',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='PURCHASE_DATE',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='TagInformation',
        ),
    ]
