# Generated by Django 2.2.4 on 2019-08-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops101', '0003_auto_20190813_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='ASSET_TAG',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='NOTES',
            field=models.CharField(default='Notes can be added here.', max_length=255),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='PURCHASE_COST',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='PURCHASE_DATE',
            field=models.DateField(),
        ),
    ]
