# Generated by Django 2.2.4 on 2019-08-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptops101', '0004_auto_20190819_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PURCHASE_DATE', models.DateField()),
                ('PURCHASE_COST', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ASSET_TAG', models.CharField(max_length=8)),
                ('HDMI', models.BooleanField(default=True)),
                ('VGA', models.BooleanField(default=False)),
                ('DISPLAY_PORT', models.BooleanField(default=True)),
                ('NOTES', models.CharField(default='Notes can be added here.', max_length=255)),
                ('ARCHETYPE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptops101.ItemArchetype')),
                ('ASSIGNED_USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laptops101.EndUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
