# Generated by Django 2.2.4 on 2019-08-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops101', '0005_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='EMAIL',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='DEPARTMENT',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='FIRST_NAME',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='LAST_NAME',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='TITLE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemarchetype',
            name='SKU',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='PURCHASE_DATE',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='MANUFACTURER',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='WEBSITE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='PURCHASE_DATE',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='enduser',
            unique_together={('FIRST_NAME', 'LAST_NAME')},
        ),
    ]
