# Generated by Django 2.2.4 on 2019-08-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops101', '0006_auto_20190823_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='ASSET_TAG',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='ASSET_TAG',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
