# Generated by Django 2.2.4 on 2019-08-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops101', '0008_auto_20190825_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='EMAIL',
            field=models.EmailField(blank=True, max_length=100, unique=True),
        ),
    ]
