# Generated by Django 2.2.4 on 2019-09-04 23:00

from django.db import migrations, models
import laptops101.customValidators


class Migration(migrations.Migration):

    dependencies = [
        ('laptops101', '0009_auto_20190825_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSET_TAG', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ASSET_TAG',
            field=models.CharField(max_length=8, unique=True, validators=[laptops101.customValidators.tag_available]),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='ASSET_TAG',
            field=models.CharField(max_length=8, unique=True, validators=[laptops101.customValidators.tag_available]),
        ),
    ]
